In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("SampleSuperstore.csv")
print("Dataset loaded successfully!")

FileNotFoundError: [Errno 2] No such file or directory: 'SampleSuperstore.csv'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df.head()
df.shape

In [ ]:
df.columns

In [ ]:
df.info

In [ ]:
df.describe()

In [ ]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_summary

In [ ]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate records:", duplicate_count)

In [ ]:
duplicates = df[df.duplicated(keep=False)]

duplicates

In [ ]:
df_cleaned = df.drop_duplicates().copy()

In [ ]:
print("Original rows:", len(df))
print("Cleaned rows:", len(df_cleaned))
print("Duplicates removed:", len(df) - len(df_cleaned))

In [ ]:
print("Remaining duplicates:", df_cleaned.duplicated().sum())

In [ ]:
df_cleaned.dtypes

In [ ]:
numeric_columns = [
    "Postal Code",
    "Sales",
    "Quantity",
    "Discount",
    "Profit"
]

for column in numeric_columns:
    print(column, ":", df_cleaned[column].dtype)

In [ ]:
categorical_columns = [
    "Ship Mode",
    "Segment",
    "Country",
    "City",
    "State",
    "Region",
    "Category",
    "Sub-Category"
]

for column in categorical_columns:
    print(column, ":", df_cleaned[column].dtype)

In [ ]:
for column in categorical_columns:
    print("\n---", column, "---")
    print(df_cleaned[column].unique())

In [ ]:
for column in categorical_columns:
    spaces = df_cleaned[column].astype(str).str.strip()
    if not df_cleaned[column].astype(str).equals(spaces):
        print("Spaces found in:", column)

In [ ]:
for column in categorical_columns:
    spaces = df_cleaned[column].astype(str).str.strip()
    if not df_cleaned[column].astype(str).equals(spaces):
        print("Spaces found in:", column)

In [ ]:
df_cleaned["Ship Mode"].value_counts()
df_cleaned["Segment"].value_counts()
df_cleaned["Region"].value_counts()
df_cleaned["Category"].value_counts()
df_cleaned["Sub-Category"].value_counts()

In [ ]:
print("Quantity <= 0:", (df_cleaned["Quantity"] <= 0).sum())
print("Sales < 0:", (df_cleaned["Sales"] < 0).sum())
print("Discount < 0:", (df_cleaned["Discount"] < 0).sum())

In [ ]:
print(df_cleaned["Postal Code"].dtype)
print(df_cleaned["Postal Code"].isnull().sum())

In [ ]:
print("===== FINAL DATA QUALITY CHECK =====")

print("Rows:", df_cleaned.shape[0])
print("Columns:", df_cleaned.shape[1])
print("Missing values:", df_cleaned.isnull().sum().sum())
print("Duplicate rows:", df_cleaned.duplicated().sum())

In [ ]:
comparison = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicate Records"
    ],
    "Before Cleaning": [
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ],
    "After Cleaning": [
        df_cleaned.shape[0],
        df_cleaned.shape[1],
        df_cleaned.isnull().sum().sum(),
        df_cleaned.duplicated().sum()
    ]
})

comparison

In [ ]:
df_cleaned.to_csv("cleaned_superstore.csv", index=False)

print("Cleaned dataset saved successfully!")

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("SampleSuperstore.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'SampleSuperstore.csv'

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("SampleSuperstore.csv")

In [10]:
print("Dataset shape:", df.shape)

Dataset shape: (9994, 13)

In [11]:
df_cleaned = df.drop_duplicates().copy()

In [12]:
print("Original rows:", len(df))
print("Cleaned rows:", len(df_cleaned))
print("Duplicates removed:", len(df) - len(df_cleaned))

Original rows: 9994
Cleaned rows: 9977
Duplicates removed: 17

In [13]:
df_cleaned.dtypes

Ship Mode        object
Segment          object
Country          object
City             object
State            object
Postal Code       int64
Region           object
Category         object
Sub-Category     object
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
dtype: object

In [14]:
data_type_summary = pd.DataFrame({
    "Column": df_cleaned.columns,
    "Data Type": df_cleaned.dtypes.astype(str).values
})

data_type_summary

          Column Data Type
0      Ship Mode    object
1        Segment    object
2        Country    object
3           City    object
4          State    object
5    Postal Code     int64
6         Region    object
7       Category    object
8   Sub-Category    object
9          Sales   float64
10      Quantity     int64
11      Discount   float64
12        Profit   float64

In [15]:
expected_numeric = ["Postal Code", "Sales", "Quantity", "Discount", "Profit"]

for column in expected_numeric:
    print(f"{column}: {df_cleaned[column].dtype}")

Postal Code: int64
Sales: float64
Quantity: int64
Discount: float64
Profit: float64

In [16]:
expected_categorical = [
    "Ship Mode",
    "Segment",
    "Country",
    "City",
    "State",
    "Region",
    "Category",
    "Sub-Category"
]

for column in expected_categorical:
    print(f"{column}: {df_cleaned[column].dtype}")

Ship Mode: object
Segment: object
Country: object
City: object
State: object
Region: object
Category: object
Sub-Category: object

In [17]:
categorical_columns = [
    "Ship Mode",
    "Segment",
    "Country",
    "City",
    "State",
    "Region",
    "Category",
    "Sub-Category"
]

for column in categorical_columns:
    print("\n==============================")
    print(column)
    print("==============================")
    print(df_cleaned[column].unique())

==============================
Ship Mode
==============================
['Second Class' 'Standard Class' 'First Class' 'Same Day']

==============================
Segment
==============================
['Consumer' 'Corporate' 'Home Office']

==============================
Country
==============================
['United States']

==============================
City
==============================
['Henderson' 'Los Angeles' 'Fort Lauderdale' 'Concord' 'Seattle'
 'Fort Worth' 'Madison' 'West Jordan' 'San Francisco' 'Fremont'
 'Philadelphia' 'Orem' 'Houston' 'Richardson' 'Naperville' 'Melbourne'
 'Eagan' 'Westland' 'Dover' 'New Albany' 'New York City' 'Troy' 'Chicago'
 'Gilbert' 'Springfield' 'Jackson' 'Memphis' 'Decatur' 'Durham' 'Columbia'
 'Rochester' 'Minneapolis' 'Portland' 'Saint Paul' 'Aurora' 'Charlotte'
 'Orland Park' 'Urbandale' 'Columbus' 'Bristol' 'Wilmington' 'Bloomington'
 'Phoenix' 'Roseville' 'Independence' 'Pasadena' 'Newark' 'Franklin'
 'Scottsdale' 'San Jose' 'Edmond' 'Carlsbad' 'San Antonio' 'Monroe'
 'Fairfield' 'Grand Prairie' 'Redlands' 'Hamilton' 'Westfield' 'Akron'
 'Denver' 'Dallas' 'Whittier' 'Saginaw' 'Medina' 'Dublin' 'Detroit'
 'Tampa' 'Santa Clara' 'Lakeville' 'San Diego' 'Brentwood' 'Chapel Hill'
 'Morristown' 'Cincinnati' 'Inglewood' 'Tamarac' 'Colorado Springs'
 'Belleville' 'Taylor' 'Lakewood' 'Arlington' 'Arvada' 'Hackensack'
 'Saint Petersburg' 'Long Beach' 'Hesperia' 'Murfreesboro' 'Layton'
 'Austin' 'Lowell' 'Manchester' 'Harlingen' 'Tucson' 'Quincy'
 'Pembroke Pines' 'Des Moines' 'Peoria' 'Las Vegas' 'Warwick' 'Miami'
 'Huntington Beach' 'Richmond' 'Louisville' 'Lawrence' 'Canton'
 'New Rochelle' 'Gastonia' 'Jacksonville' 'Auburn' 'Norman' 'Park Ridge'
 'Amarillo' 'Lindenhurst' 'Huntsville' 'Fayetteville' 'Costa Mesa'
 'Parker' 'Atlanta' 'Gladstone' 'Great Falls' 'Lakeland' 'Montgomery'
 'Mesa' 'Green Bay' 'Anaheim' 'Marysville' 'Salem' 'Laredo' 'Grove City'
 'Dearborn' 'Warner Robins' 'Vallejo' 'Mission Viejo' 'Rochester Hills'
 'Plainfield' 'Sierra Vista' 'Vancouver' 'Cleveland' 'Tyler' 'Burlington'
 'Waynesboro' 'Chester' 'Cary' 'Palm Coast' 'Mount Vernon' 'Hialeah'
 'Oceanside' 'Evanston' 'Trenton' 'Cottage Grove' 'Bossier City'
 'Lancaster' 'Asheville' 'Lake Elsinore' 'Omaha' 'Edmonds' 'Santa Ana'
 'Milwaukee' 'Florence' 'Lorain' 'Linden' 'Salinas' 'New Brunswick'
 'Garland' 'Norwich' 'Alexandria' 'Toledo' 'Farmington' 'Riverside'
 'Torrance' 'Round Rock' 'Boca Raton' 'Virginia Beach' 'Murrieta'
 'Olympia' 'Washington' 'Jefferson City' 'Saint Peters' 'Rockford'
 'Brownsville' 'Yonkers' 'Oakland' 'Clinton' 'Encinitas' 'Roswell'
 'Jonesboro' 'Antioch' 'Homestead' 'La Porte' 'Lansing' 'Cuyahoga Falls'
 'Reno' 'Harrisonburg' 'Escondido' 'Royal Oak' 'Rockville' 'Coral Springs'
 'Buffalo' 'Boynton Beach' 'Gulfport' 'Fresno' 'Greenville' 'Macon'
 'Cedar Rapids' 'Providence' 'Pueblo' 'Deltona' 'Murray' 'Middletown'
 'Freeport' 'Pico Rivera' 'Provo' 'Pleasant Grove' 'Smyrna' 'Parma'
 'Mobile' 'New Bedford' 'Irving' 'Vineland' 'Glendale' 'Niagara Falls'
 'Thomasville' 'Westminster' 'Coppell' 'Pomona' 'North Las Vegas'
 'Allentown' 'Tempe' 'Laguna Niguel' 'Bridgeton' 'Everett' 'Watertown'
 'Appleton' 'Bellevue' 'Allen' 'El Paso' 'Grapevine' 'Carrollton' 'Kent'
 'Lafayette' 'Tigard' 'Skokie' 'Plano' 'Suffolk' 'Indianapolis' 'Bayonne'
 'Greensboro' 'Baltimore' 'Kenosha' 'Olathe' 'Tulsa' 'Redmond' 'Raleigh'
 'Muskogee' 'Meriden' 'Bowling Green' 'South Bend' 'Spokane' 'Keller'
 'Port Orange' 'Medford' 'Charlottesville' 'Missoula' 'Apopka' 'Reading'
 'Broomfield' 'Paterson' 'Oklahoma City' 'Chesapeake' 'Lubbock'
 'Johnson City' 'San Bernardino' 'Leominster' 'Bozeman' 'Perth Amboy'
 'Ontario' 'Rancho Cucamonga' 'Moorhead' 'Mesquite' 'Stockton'
 'Ormond Beach' 'Sunnyvale' 'York' 'College Station' 'Saint Louis'
 'Manteca' 'San Angelo' 'Salt Lake City' 'Knoxville' 'Little Rock'
 'Lincoln Park' 'Marion' 'Littleton' 'Bangor' 'Southaven' 'New Castle'
 'Midland' 'Sioux Falls' 'Fort Collins' 'Clarksville' 'Sacramento'
 'Thousand Oaks' 'Malden' 'Holyoke' 'Albuquerque' 'Sparks' 'Coachella'
 'Elmhurst' 'Passaic' 'North Charleston' 'Newport News' 'Jamestown'
 'Mishawaka' 'La Quinta' 'Tallahassee' 'Nashville' 'Bellingham'
 'Woodstock' 'Haltom City' 'Wheeling' 'Summerville' 'Hot Springs'
 'Englewood' 'Las Cruces' 'Hoover' 'Frisco' 'Vacaville' 'Waukesha'
 'Bakersfield' 'Pompano Beach' 'Corpus Christi' 'Redondo Beach' 'Orlando'
 'Orange' 'Lake Charles' 'Highland Park' 'Hempstead' 'Noblesville'
 'Apple Valley' 'Mount Pleasant' 'Sterling Heights' 'Eau Claire' 'Pharr'
 'Billings' 'Gresham' 'Chattanooga' 'Meridian' 'Bolingbrook' 'Maple Grove'
 'Woodland' 'Missouri City' 'Pearland' 'San Mateo' 'Grand Rapids'
 'Visalia' 'Overland Park' 'Temecula' 'Yucaipa' 'Revere' 'Conroe'
 'Tinley Park' 'Dubuque' 'Dearborn Heights' 'Santa Fe' 'Hickory'
 'Carol Stream' 'Saint Cloud' 'North Miami' 'Plantation'
 'Port Saint Lucie' 'Rock Hill' 'Odessa' 'West Allis' 'Chula Vista'
 'Manhattan' 'Altoona' 'Thornton' 'Champaign' 'Texarkana' 'Edinburg'
 'Baytown' 'Greenwood' 'Woonsocket' 'Superior' 'Bedford' 'Covington'
 'Broken Arrow' 'Miramar' 'Hollywood' 'Deer Park' 'Wichita' 'Mcallen'
 'Iowa City' 'Boise' 'Cranston' 'Port Arthur' 'Citrus Heights'
 'The Colony' 'Daytona Beach' 'Bullhead City' 'Portage' 'Fargo' 'Elkhart'
 'San Gabriel' 'Margate' 'Sandy Springs' 'Mentor' 'Lawton' 'Hampton'
 'Rome' 'La Crosse' 'Lewiston' 'Hattiesburg' 'Danville' 'Logan'
 'Waterbury' 'Athens' 'Avondale' 'Marietta' 'Yuma' 'Wausau' 'Pasco'
 'Oak Park' 'Pensacola' 'League City' 'Gaithersburg' 'Lehi' 'Tuscaloosa'
 'Moreno Valley' 'Georgetown' 'Loveland' 'Chandler' 'Helena' 'Kirkwood'
 'Waco' 'Frankfort' 'Bethlehem' 'Grand Island' 'Woodbury' 'Rogers'
 'Clovis' 'Jupiter' 'Santa Barbara' 'Cedar Hill' 'Norfolk' 'Draper'
 'Ann Arbor' 'La Mesa' 'Pocatello' 'Holland' 'Milford' 'Buffalo Grove'
 'Lake Forest' 'Redding' 'Chico' 'Utica' 'Conway' 'Cheyenne' 'Owensboro'
 'Caldwell' 'Kenner' 'Nashua' 'Bartlett' 'Redwood City' 'Lebanon'
 'Santa Maria' 'Des Plaines' 'Longview' 'Hendersonville' 'Waterloo'
 'Cambridge' 'Palatine' 'Beverly' 'Eugene' 'Oxnard' 'Renton' 'Glenview'
 'Delray Beach' 'Commerce City' 'Texas City' 'Wilson' 'Rio Rancho'
 'Goldsboro' 'Montebello' 'El Cajon' 'Beaumont' 'West Palm Beach'
 'Abilene' 'Normal' 'Saint Charles' 'Camarillo' 'Hillsboro' 'Burbank'
 'Modesto' 'Garden City' 'Atlantic City' 'Longmont' 'Davis' 'Morgan Hill'
 'Clifton' 'Sheboygan' 'East Point' 'Rapid City' 'Andover' 'Kissimmee'
 'Shelton' 'Danbury' 'Sanford' 'San Marcos' 'Greeley' 'Mansfield' 'Elyria'
 'Twin Falls' 'Coral Gables' 'Romeoville' 'Marlborough' 'Laurel' 'Bryan'
 'Pine Bluff' 'Aberdeen' 'Hagerstown' 'East Orange' 'Arlington Heights'
 'Oswego' 'Coon Rapids' 'San Clemente' 'San Luis Obispo' 'Springdale'
 'Lodi' 'Mason']

==============================
State
==============================
['Kentucky' 'California' 'Florida' 'North Carolina' 'Washington' 'Texas'
 'Wisconsin' 'Utah' 'Nebraska' 'Pennsylvania' 'Illinois' 'Minnesota'
 'Michigan' 'Delaware' 'Indiana' 'New York' 'Arizona' 'Virginia'
 'Tennessee' 'Alabama' 'South Carolina' 'Oregon' 'Colorado' 'Iowa' 'Ohio'
 'Missouri' 'Oklahoma' 'New Mexico' 'Louisiana' 'Connecticut' 'New Jersey'
 'Massachusetts' 'Georgia' 'Nevada' 'Rhode Island' 'Mississippi'
 'Arkansas' 'Montana' 'New Hampshire' 'Maryland' 'District of Columbia'
 'Kansas' 'Vermont' 'Maine' 'South Dakota' 'Idaho' 'North Dakota'
 'Wyoming' 'West Virginia']

==============================
Region
==============================
['South' 'West' 'Central' 'East']

==============================
Category
==============================
['Furniture' 'Office Supplies' 'Technology']

==============================
Sub-Category
==============================
['Bookcases' 'Chairs' 'Labels' 'Tables' 'Storage' 'Furnishings' 'Art'
 'Phones' 'Binders' 'Appliances' 'Paper' 'Accessories' 'Envelopes'
 'Fasteners' 'Supplies' 'Machines' 'Copiers']

In [18]:


for column in categorical_columns:
    leading_trailing_spaces = (
        df_cleaned[column].astype(str) !=
        df_cleaned[column].astype(str).str.strip()
    ).sum()

    print(f"{column}: {leading_trailing_spaces} values with extra spaces")

Ship Mode: 0 values with extra spaces
Segment: 0 values with extra spaces
Country: 0 values with extra spaces
City: 0 values with extra spaces
State: 0 values with extra spaces
Region: 0 values with extra spaces
Category: 0 values with extra spaces
Sub-Category: 0 values with extra spaces

In [19]:
print("Quantity <= 0:", (df_cleaned["Quantity"] <= 0).sum())
print("Sales < 0:", (df_cleaned["Sales"] < 0).sum())
print("Discount < 0:", (df_cleaned["Discount"] < 0).sum())
print("Discount > 1:", (df_cleaned["Discount"] > 1).sum())

#profit Range
print("Minimum Profit:", df_cleaned["Profit"].min())
print("Maximum Profit:", df_cleaned["Profit"].max())

#Check Sales and Quantity ranges
print("Minimum Sales:", df_cleaned["Sales"].min())
print("Maximum Sales:", df_cleaned["Sales"].max())

print("Minimum Quantity:", df_cleaned["Quantity"].min())
print("Maximum Quantity:", df_cleaned["Quantity"].max())

Quantity <= 0: 0
Sales < 0: 0
Discount < 0: 0
Discount > 1: 0
Minimum Profit: -6599.978
Maximum Profit: 8399.976
Minimum Sales: 0.444
Maximum Sales: 22638.48
Minimum Quantity: 1
Maximum Quantity: 14

In [20]:
print("========== FINAL DATA QUALITY REPORT ==========")

print("Original rows:", df.shape[0])
print("Final rows:", df_cleaned.shape[0])
print("Columns:", df_cleaned.shape[1])

print("\nMissing values:")
print(df_cleaned.isnull().sum().sum())

print("\nDuplicate records:")
print(df_cleaned.duplicated().sum())

print("\nData types:")
print(df_cleaned.dtypes)

========== FINAL DATA QUALITY REPORT ==========
Original rows: 9994
Final rows: 9977
Columns: 13

Missing values:
0

Duplicate records:
0

Data types:
Ship Mode        object
Segment          object
Country          object
City             object
State            object
Postal Code       int64
Region           object
Category         object
Sub-Category     object
Sales           float64
Quantity          int64
Discount        float64
Profit          float64
dtype: object

In [21]:
comparison = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicate Records"
    ],
    "Before Cleaning": [
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ],
    "After Cleaning": [
        df_cleaned.shape[0],
        df_cleaned.shape[1],
        df_cleaned.isnull().sum().sum(),
        df_cleaned.duplicated().sum()
    ]
})

comparison

              Metric  Before Cleaning  After Cleaning
0               Rows             9994            9977
1            Columns               13              13
2     Missing Values                0               0
3  Duplicate Records               17               0

In [22]:
df_cleaned.to_csv("cleaned_superstore.csv", index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!

In [23]:
import os

print("File exists:", os.path.exists("cleaned_superstore.csv"))

File exists: True